/* TODO:
 * We do not want the texprintf library to errorexit all the time
 * It should rather give up parsing and set some error flags
 */
#include "errorflags.h" /* generated by gen_errorflags.sh, defines error flags */

extern char *ssdp_error_messages[];
extern int ssdp_error_state;	/* signals error occurred, if 0 everything is OK */
void AddErr(int ERRFLAG); /* call to set an error flag as defined in errorflags.h */
int QueryErr(int ERRFLAG);
void E_Messages();
void ResetErrors();
