#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "error.h"
#include "errormessages.h" /* generated by gen_errorflags.sh, defines error messages for eachg error flag */

int ssdp_error_state=0;			/* single boolean indicating whether there were any errors */
char ERRORS[NERR] = {0};	/* zero initialized error flags */

void AddErr(int ERRFLAG)
{
	ssdp_error_state=1;
	if (ERRFLAG>NERR)
	{
		/* the recursive error :) */
		// ERRORFLAG ERROUTRANGE  "Error flag out of range!"
		AddErr(ERROUTRANGE);
	}
	else
		ERRORS[ERRFLAG]++;
}
int QueryErr(int ERRFLAG)
{
	if (ERRFLAG>NERR)
		AddErr(ERROUTRANGE);
	if (ERRORS[ERRFLAG])
		return 1;
	return 0;
}

void E_Messages()
{
	int i;
	for (i=0;i<NERR;i++)
		if (ERRORS[i])
			fprintf(stderr,"ERROR: %s (%dx)\n",  ssdp_error_messages[i], ERRORS[i]);
}

void ResetErrors()
{
	int i;
	for (i=0;i<NERR;i++)
		ERRORS[i]=0;
	ssdp_error_state=0;
}
